# Generated by Django 4.2 on 2023-06-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.FilePathField(default='')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'unique_together': {('file', 'path')},
            },
        ),
    ]
