# Generated by Django 4.2 on 2023-06-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_skin_detect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoloImage',
            fields=[
                ('file', models.FileField(blank=True, null=True, unique=True, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.FilePathField(default='/Users/csb01/Desktop/assignment/capstone/disease_detection/media', path='/Users/csb01/Desktop/assignment/capstone/disease_detection/media')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'unique_together': {('file', 'path')},
            },
        ),
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
